# ****************************************************************
# Config, and use common Makefile from one level up

CPU  ?= Fife
RV   ?= RV32

TOPFILE := ./Top.bsv
EXEFILE := exe_Test_SB

include ../../Build/Include.mk

# ****************************************************************
